"""BTC Options Signal Engine - Live Market Scanner
==============================================================================
Fetches live BTC data from public APIs, computes all required technical
indicators, and checks all 4 strategy entry conditions against current
market state.

Data sources:
  - Deribit public API: BTC index price, BTC-PERPETUAL OHLCV, DVOL
  - CoinGecko API: Fallback for historical price data
"""

import sys
import os
import math
import json
import time
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, asdict

import numpy as np
import httpx

sys.path.insert(0, '/home/user/files')

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DERIBIT_PUBLIC = 'https://www.deribit.com/api/v2'

# Regime thresholds (from the research: btc_vol_regimes.csv)
# These match the original system's threshold-based regime classification
REGIME_THRESHOLDS = {
    'LOW': (0.0, 0.40),
    'MEDIUM': (0.40, 0.65),
    'HIGH': (0.65, 0.90),
    'CRISIS': (0.90, float('inf')),
}


@dataclass
class MarketSnapshot:
    """Current market state with all computed indicators."""
    timestamp: str
    btc_price: float
    # Volatility
    rv_cc_30d: float
    rv_cc_7d: float
    iv_30d: float           # Deribit DVOL or synthetic IV
    vrp_30d: float          # IV - RV (vol risk premium)
    vrp_zscore: float
    vov_30d: float          # Vol-of-vol
    vov_5d_avg: float       # 5-day average VoV
    # Technical
    rsi_14: float
    ret_5d: float
    ret_10d: float
    sma_50: float
    sma_200: float
    atr_14: float
    # Regime
    regime: str
    days_in_regime: int
    # Percentiles
    rv_percentile: float
    # Raw arrays (for strategy use)
    close_prices: List[float]

    def to_dict(self) -> dict:
        d = asdict(self)
        d.pop('close_prices', None)  # Don't serialize full array
        return d


@dataclass
class LiveSignal:
    """Signal generated by live scanning."""
    strategy_name: str
    signal_type: str        # 'iron_condor', 'long_otm_call', etc.
    direction: str          # 'long' or 'short'
    description: str
    confidence: str         # 'HIGH', 'MEDIUM', 'LOW'
    # Option details
    suggested_instrument: str
    suggested_strike: float
    suggested_expiry: str
    option_type: str
    # Sizing
    suggested_size_btc: float
    max_loss_usd: float
    # Legs (for multi-leg)
    legs: List[Dict]
    # Entry conditions met
    conditions_met: List[str]

    def to_dict(self) -> dict:
        return asdict(self)


class DeribitSignalEngine:
    """Live market scanner that computes indicators and checks strategy signals."""

    def __init__(self, lookback_days: int = 120, equity: float = 100.0):
        self.lookback_days = lookback_days
        self.equity = equity
        self.client = httpx.Client(timeout=30)
        self._snapshot: Optional[MarketSnapshot] = None

    # -----------------------------------------------------------------
    # Public API Data Fetching
    # -----------------------------------------------------------------
    def get_btc_price(self) -> float:
        """Fetch current BTC/USD index price from Deribit."""
        try:
            r = self.client.get(
                f'{DERIBIT_PUBLIC}/public/get_index_price',
                params={'index_name': 'btc_usd'}
            )
            data = r.json()
            return data['result']['index_price']
        except Exception as e:
            print(f'Deribit price fetch failed: {e}')
            # Fallback to CoinGecko
            try:
                r = self.client.get(
                    'https://api.coingecko.com/api/v3/simple/price',
                    params={'ids': 'bitcoin', 'vs_currencies': 'usd'}
                )
                return float(r.json()['bitcoin']['usd'])
            except Exception as e2:
                print(f'CoinGecko price fetch also failed: {e2}')
                return 0.0

    def get_dvol(self) -> float:
        """Fetch Deribit DVOL (30-day implied volatility index) via volatility index data."""
        try:
            end_ts = int(time.time() * 1000)
            start_ts = end_ts - 3600000  # Last hour
            r = self.client.get(
                f'{DERIBIT_PUBLIC}/public/get_volatility_index_data',
                params={
                    'currency': 'BTC',
                    'resolution': 3600,
                    'start_timestamp': start_ts,
                    'end_timestamp': end_ts,
                }
            )
            data = r.json()
            result = data.get('result', {})
            vol_data = result.get('data', [])
            if vol_data:
                # Each entry: [timestamp, open, high, low, close]
                latest = vol_data[-1]
                dvol_pct = latest[4]  # close value (e.g., 58.96 = 58.96%)
                return dvol_pct / 100.0  # Convert to decimal (0.5896)
            return 0.0
        except Exception as e:
            print(f'DVOL fetch failed: {e}')
            return 0.0

    def get_historical_ohlcv(self, days: int = 120) -> List[Dict]:
        """Fetch daily OHLCV from Deribit BTC-PERPETUAL TradingView chart data."""
        try:
            end_ts = int(time.time() * 1000)
            start_ts = end_ts - (days * 24 * 60 * 60 * 1000)

            r = self.client.get(
                f'{DERIBIT_PUBLIC}/public/get_tradingview_chart_data',
                params={
                    'instrument_name': 'BTC-PERPETUAL',
                    'resolution': 'D',  # Daily
                    'start_timestamp': start_ts,
                    'end_timestamp': end_ts,
                }
            )
            data = r.json()
            result = data.get('result', {})

            if result.get('status') != 'ok':
                raise ValueError(f'Deribit chart status: {result.get("status")}')

            ticks = result.get('ticks', [])
            opens = result.get('open', [])
            highs = result.get('high', [])
            lows = result.get('low', [])
            closes = result.get('close', [])
            volumes = result.get('volume', [])

            ohlcv = []
            for i in range(len(ticks)):
                ohlcv.append({
                    'date': datetime.fromtimestamp(ticks[i] / 1000, tz=timezone.utc).strftime('%Y-%m-%d'),
                    'open': opens[i],
                    'high': highs[i],
                    'low': lows[i],
                    'close': closes[i],
                    'volume': volumes[i] if i < len(volumes) else 0,
                })
            return ohlcv

        except Exception as e:
            print(f'Deribit OHLCV fetch failed: {e}')
            # Fallback to CoinGecko
            return self._get_coingecko_ohlcv(days)

    def _get_coingecko_ohlcv(self, days: int) -> List[Dict]:
        """Fallback: fetch from CoinGecko (close-only, no intraday OHLC)."""
        try:
            r = self.client.get(
                'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart',
                params={'vs_currency': 'usd', 'days': days, 'interval': 'daily'}
            )
            data = r.json()
            prices = data.get('prices', [])
            result = []
            for ts, price in prices:
                dt = datetime.fromtimestamp(ts / 1000, tz=timezone.utc)
                result.append({
                    'date': dt.strftime('%Y-%m-%d'),
                    'open': price,
                    'high': price,
                    'low': price,
                    'close': price,
                    'volume': 0,
                })
            return result
        except Exception as e:
            print(f'CoinGecko OHLCV fetch also failed: {e}')
            return []
