"""BTC Options Signal Engine - Live Market Scanner
==============================================================================
Fetches live BTC data from public APIs, computes all required technical
indicators, and checks all 4 strategy entry conditions against current
market state.

Data sources:
  - Deribit public API: BTC index price, BTC-PERPETUAL OHLCV, DVOL
  - CoinGecko API: Fallback for historical price data
"""

import sys
import os
import math
import json
import time
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, asdict

import numpy as np
import httpx

sys.path.insert(0, '/home/user/files')

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DERIBIT_PUBLIC = 'https://www.deribit.com/api/v2'

# Regime thresholds (from the research: btc_vol_regimes.csv)
# These match the original system's threshold-based regime classification
REGIME_THRESHOLDS = {
    'LOW': (0.0, 0.40),
    'MEDIUM': (0.40, 0.65),
    'HIGH': (0.65, 0.90),
    'CRISIS': (0.90, float('inf')),
}


@dataclass
class MarketSnapshot:
    """Current market state with all computed indicators."""
    timestamp: str
    btc_price: float
    # Volatility
    rv_cc_30d: float
    rv_cc_7d: float
    iv_30d: float           # Deribit DVOL or synthetic IV
    vrp_30d: float          # IV - RV (vol risk premium)
    vrp_zscore: float
    vov_30d: float          # Vol-of-vol
    vov_5d_avg: float       # 5-day average VoV
    # Technical
    rsi_14: float
    ret_5d: float
    ret_10d: float
    sma_50: float
    sma_200: float
    atr_14: float
    # Regime
    regime: str
    days_in_regime: int
    # Percentiles
    rv_percentile: float
    # Raw arrays (for strategy use)
    close_prices: List[float]

    def to_dict(self) -> dict:
        d = asdict(self)
        d.pop('close_prices', None)  # Don't serialize full array
        return d


@dataclass
class LiveSignal:
    """Signal generated by live scanning."""
    strategy_name: str
    signal_type: str        # 'iron_condor', 'long_otm_call', etc.
    direction: str          # 'long' or 'short'
    description: str
    confidence: str         # 'HIGH', 'MEDIUM', 'LOW'
    # Option details
    suggested_instrument: str
    suggested_strike: float
    suggested_expiry: str
    option_type: str
    # Sizing
    suggested_size_btc: float
    max_loss_usd: float
    # Legs (for multi-leg)
    legs: List[Dict]
    # Entry conditions met
    conditions_met: List[str]
    confidence_score: float = 0.0  # Numeric 0-1 from ConfidenceScorer

    def to_dict(self) -> dict:
        return asdict(self)


class DeribitSignalEngine:
    """Live market scanner that computes indicators and checks strategy signals."""

    def __init__(self, lookback_days: int = 120, equity: float = 100.0):
        self.lookback_days = lookback_days
        self.equity = equity
        self.client = httpx.Client(timeout=30)
        self._snapshot: Optional[MarketSnapshot] = None

    # -----------------------------------------------------------------
    # Public API Data Fetching
    # -----------------------------------------------------------------
    def get_btc_price(self) -> float:
        """Fetch current BTC/USD index price from Deribit."""
        try:
            r = self.client.get(
                f'{DERIBIT_PUBLIC}/public/get_index_price',
                params={'index_name': 'btc_usd'}
            )
            data = r.json()
            return data['result']['index_price']
        except Exception as e:
            print(f'Deribit price fetch failed: {e}')
            # Fallback to CoinGecko
            try:
                r = self.client.get(
                    'https://api.coingecko.com/api/v3/simple/price',
                    params={'ids': 'bitcoin', 'vs_currencies': 'usd'}
                )
                return float(r.json()['bitcoin']['usd'])
            except Exception as e2:
                print(f'CoinGecko price fetch also failed: {e2}')
                return 0.0

    def get_dvol(self) -> float:
        """Fetch Deribit DVOL (30-day implied volatility index) via volatility index data."""
        try:
            end_ts = int(time.time() * 1000)
            start_ts = end_ts - 3600000  # Last hour
            r = self.client.get(
                f'{DERIBIT_PUBLIC}/public/get_volatility_index_data',
                params={
                    'currency': 'BTC',
                    'resolution': 3600,
                    'start_timestamp': start_ts,
                    'end_timestamp': end_ts,
                }
            )
            data = r.json()
            result = data.get('result', {})
            vol_data = result.get('data', [])
            if vol_data:
                # Each entry: [timestamp, open, high, low, close]
                latest = vol_data[-1]
                dvol_pct = latest[4]  # close value (e.g., 58.96 = 58.96%)
                return dvol_pct / 100.0  # Convert to decimal (0.5896)
            return 0.0
        except Exception as e:
            print(f'DVOL fetch failed: {e}')
            return 0.0

    def get_historical_ohlcv(self, days: int = 120) -> List[Dict]:
        """Fetch daily OHLCV from Deribit BTC-PERPETUAL TradingView chart data."""
        try:
            end_ts = int(time.time() * 1000)
            start_ts = end_ts - (days * 24 * 60 * 60 * 1000)

            r = self.client.get(
                f'{DERIBIT_PUBLIC}/public/get_tradingview_chart_data',
                params={
                    'instrument_name': 'BTC-PERPETUAL',
                    'resolution': 'D',  # Daily
                    'start_timestamp': start_ts,
                    'end_timestamp': end_ts,
                }
            )
            data = r.json()
            result = data.get('result', {})

            if result.get('status') != 'ok':
                raise ValueError(f'Deribit chart status: {result.get("status")}')

            ticks = result.get('ticks', [])
            opens = result.get('open', [])
            highs = result.get('high', [])
            lows = result.get('low', [])
            closes = result.get('close', [])
            volumes = result.get('volume', [])

            ohlcv = []
            for i in range(len(ticks)):
                ohlcv.append({
                    'date': datetime.fromtimestamp(ticks[i] / 1000, tz=timezone.utc).strftime('%Y-%m-%d'),
                    'open': opens[i],
                    'high': highs[i],
                    'low': lows[i],
                    'close': closes[i],
                    'volume': volumes[i] if i < len(volumes) else 0,
                })
            return ohlcv

        except Exception as e:
            print(f'Deribit OHLCV fetch failed: {e}')
            # Fallback to CoinGecko
            return self._get_coingecko_ohlcv(days)

    def _get_coingecko_ohlcv(self, days: int) -> List[Dict]:
        """Fallback: fetch from CoinGecko (close-only, no intraday OHLC)."""
        try:
            r = self.client.get(
                'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart',
                params={'vs_currency': 'usd', 'days': days, 'interval': 'daily'}
            )
            data = r.json()
            prices = data.get('prices', [])
            result = []
            for ts, price in prices:
                dt = datetime.fromtimestamp(ts / 1000, tz=timezone.utc)
                result.append({
                    'date': dt.strftime('%Y-%m-%d'),
                    'open': price,
                    'high': price,
                    'low': price,
                    'close': price,
                    'volume': 0,
                })
            return result
        except Exception as e:
            print(f'CoinGecko OHLCV fetch also failed: {e}')
            return []

    # -----------------------------------------------------------------
    # Indicator Computation
    # -----------------------------------------------------------------
    @staticmethod
    def compute_rv_cc(closes: List[float], window: int) -> float:
        """Close-to-close realized volatility (annualized)."""
        if len(closes) < window + 1:
            return 0.0
        log_returns = [math.log(closes[i] / closes[i-1])
                       for i in range(len(closes) - window, len(closes))]
        if len(log_returns) < 2:
            return 0.0
        std = np.std(log_returns, ddof=1)
        return std * math.sqrt(365)  # Annualized (crypto = 365 days)

    @staticmethod
    def compute_rsi(closes: List[float], period: int = 14) -> float:
        """Relative Strength Index."""
        if len(closes) < period + 1:
            return 50.0
        deltas = [closes[i] - closes[i-1] for i in range(1, len(closes))]
        recent = deltas[-period:]
        gains = [d for d in recent if d > 0]
        losses = [-d for d in recent if d < 0]
        avg_gain = sum(gains) / period if gains else 0
        avg_loss = sum(losses) / period if losses else 0.0001
        rs = avg_gain / avg_loss
        return 100.0 - (100.0 / (1.0 + rs))

    @staticmethod
    def compute_atr(highs: List[float], lows: List[float], closes: List[float],
                    period: int = 14) -> float:
        """Average True Range."""
        if len(closes) < period + 1:
            return 0.0
        trs = []
        for i in range(len(closes) - period, len(closes)):
            if i == 0:
                tr = highs[i] - lows[i]
            else:
                tr = max(highs[i] - lows[i],
                         abs(highs[i] - closes[i-1]),
                         abs(lows[i] - closes[i-1]))
            trs.append(tr)
        return sum(trs) / len(trs)

    @staticmethod
    def compute_vov(closes: List[float], window: int = 30) -> Tuple[float, float]:
        """Vol-of-vol: std of rolling 7d RV values over the window.
        Returns (current_vov, 5d_average_vov).
        """
        if len(closes) < window + 10:
            return 0.0, 0.0

        # Compute 7d RV for each day over the lookback
        daily_rvs = []
        for i in range(7, len(closes)):
            sub = closes[i-7:i+1]
            if len(sub) >= 2:
                lr = [math.log(sub[j]/sub[j-1]) for j in range(1, len(sub))]
                rv = np.std(lr, ddof=1) * math.sqrt(365) if len(lr) > 1 else 0.0
                daily_rvs.append(rv)

        if len(daily_rvs) < window:
            return 0.0, 0.0

        # Current VoV: std of last `window` daily RV values
        current_vov = np.std(daily_rvs[-window:], ddof=1)

        # 5-day trailing average of VoV
        vov_series = []
        for i in range(window, len(daily_rvs) + 1):
            vov_series.append(np.std(daily_rvs[i-window:i], ddof=1))

        if len(vov_series) >= 5:
            vov_5d_avg = np.mean(vov_series[-5:])
        else:
            vov_5d_avg = current_vov

        return float(current_vov), float(vov_5d_avg)

    @staticmethod
    def classify_regime(rv_30d: float) -> str:
        """Classify volatility regime based on 30d RV."""
        for regime, (low, high) in REGIME_THRESHOLDS.items():
            if low <= rv_30d < high:
                return regime
        return 'HIGH'

    def compute_vrp_zscore(self, vrp_30d: float, closes: List[float],
                           iv_30d: float) -> float:
        """Compute VRP z-score using rolling history of VRP estimates."""
        if len(closes) < 90:
            return 0.0

        # Compute rolling VRP values using synthetic IV estimate
        # (since we only have DVOL for current, not historical)
        vrp_values = []
        for i in range(60, len(closes)):
            rv = self.compute_rv_cc(closes[:i+1], 30)
            if rv > 0:
                # Approximate historical IV as rv * premium_factor
                iv_est = rv * 1.15
                vrp = iv_est - rv
                vrp_values.append(vrp)

        if len(vrp_values) < 10:
            return 0.0

        recent = vrp_values[-30:] if len(vrp_values) >= 30 else vrp_values
        mean_vrp = np.mean(recent)
        std_vrp = np.std(recent, ddof=1)
        if std_vrp < 0.001:
            return 0.0
        return (vrp_30d - mean_vrp) / std_vrp

    def compute_rv_percentile(self, current_rv: float, closes: List[float]) -> float:
        """Compute percentile rank of current RV vs recent history."""
        if len(closes) < 90:
            return 50.0
        rv_values = []
        for i in range(30, len(closes)):
            rv = self.compute_rv_cc(closes[:i+1], 30)
            if rv > 0:
                rv_values.append(rv)
        if not rv_values:
            return 50.0
        below = sum(1 for v in rv_values if v < current_rv)
        return (below / len(rv_values)) * 100.0

    # -----------------------------------------------------------------
    # Full Market Snapshot
    # -----------------------------------------------------------------
    def build_snapshot(self) -> MarketSnapshot:
        """Fetch all data and compute full market snapshot."""
        print('Fetching BTC price from Deribit...')
        btc_price = self.get_btc_price()
        print(f'  BTC Price: ${btc_price:,.2f}')

        print('Fetching DVOL (30d implied vol)...')
        dvol = self.get_dvol()
        if dvol > 0:
            print(f'  DVOL: {dvol*100:.1f}%')
        else:
            print('  DVOL: unavailable, will use synthetic IV')

        print(f'Fetching {self.lookback_days}d historical OHLCV from Deribit...')
        ohlcv = self.get_historical_ohlcv(self.lookback_days)
        print(f'  Got {len(ohlcv)} daily bars')

        if not ohlcv:
            print('ERROR: No historical data available')
            return MarketSnapshot(
                timestamp=datetime.now(timezone.utc).isoformat(),
                btc_price=btc_price, rv_cc_30d=0, rv_cc_7d=0,
                iv_30d=dvol or 0.6, vrp_30d=0, vrp_zscore=0,
                vov_30d=0, vov_5d_avg=0, rsi_14=50, ret_5d=0,
                ret_10d=0, sma_50=btc_price, sma_200=btc_price,
                atr_14=0, regime='MEDIUM', days_in_regime=1,
                rv_percentile=50, close_prices=[btc_price]
            )

        closes = [bar['close'] for bar in ohlcv]
        highs = [bar['high'] for bar in ohlcv]
        lows = [bar['low'] for bar in ohlcv]

        # Append current price as latest if significantly different from last bar
        if btc_price > 0 and closes and abs(closes[-1] - btc_price) / btc_price > 0.005:
            closes.append(btc_price)
            highs.append(max(btc_price, closes[-1]) if len(closes) > 1 else btc_price)
            lows.append(min(btc_price, closes[-1]) if len(closes) > 1 else btc_price)

        print('Computing indicators...')

        # Realized volatility
        rv_30d = self.compute_rv_cc(closes, 30)
        rv_7d = self.compute_rv_cc(closes, 7)

        # Implied volatility (use DVOL if available, else synthetic)
        iv_30d = dvol if dvol > 0 else rv_30d * 1.15

        # VRP
        vrp_30d = iv_30d - rv_30d

        # VRP z-score
        vrp_zscore = self.compute_vrp_zscore(vrp_30d, closes, iv_30d)

        # Vol-of-vol
        vov_30d, vov_5d_avg = self.compute_vov(closes, 30)

        # RSI
        rsi_14 = self.compute_rsi(closes, 14)

        # Returns
        ret_5d = (closes[-1] / closes[-6] - 1) if len(closes) >= 6 else 0.0
        ret_10d = (closes[-1] / closes[-11] - 1) if len(closes) >= 11 else 0.0

        # SMAs
        sma_50 = float(np.mean(closes[-50:])) if len(closes) >= 50 else float(np.mean(closes))
        sma_200 = float(np.mean(closes[-200:])) if len(closes) >= 200 else float(np.mean(closes))

        # ATR
        atr_14 = self.compute_atr(highs, lows, closes, 14)

        # Regime
        regime = self.classify_regime(rv_30d)

        # Days in regime (check how many consecutive days share the same regime)
        days_in_regime = 1
        for i in range(len(closes) - 2, max(0, len(closes) - 60), -1):
            if i < 31:
                break
            hist_rv = self.compute_rv_cc(closes[:i+1], 30)
            hist_regime = self.classify_regime(hist_rv)
            if hist_regime == regime:
                days_in_regime += 1
            else:
                break

        # RV percentile
        rv_pctl = self.compute_rv_percentile(rv_30d, closes)

        snapshot = MarketSnapshot(
            timestamp=datetime.now(timezone.utc).isoformat(),
            btc_price=btc_price,
            rv_cc_30d=round(rv_30d, 4),
            rv_cc_7d=round(rv_7d, 4),
            iv_30d=round(iv_30d, 4),
            vrp_30d=round(vrp_30d, 4),
            vrp_zscore=round(vrp_zscore, 2),
            vov_30d=round(vov_30d, 4),
            vov_5d_avg=round(vov_5d_avg, 4),
            rsi_14=round(rsi_14, 1),
            ret_5d=round(ret_5d, 4),
            ret_10d=round(ret_10d, 4),
            sma_50=round(sma_50, 2),
            sma_200=round(sma_200, 2),
            atr_14=round(atr_14, 2),
            regime=regime,
            days_in_regime=days_in_regime,
            rv_percentile=round(rv_pctl, 1),
            close_prices=closes,
        )

        self._snapshot = snapshot
        print(f'  Regime: {regime} (RV={rv_30d*100:.1f}%, IV={iv_30d*100:.1f}%)')
        print(f'  VRP: {vrp_30d*100:.1f}%, z={vrp_zscore:.2f}')
        print(f'  RSI: {rsi_14:.1f}, VoV: {vov_30d:.4f}')
        print(f'  5d Ret: {ret_5d*100:+.1f}%, RV Pctl: {rv_pctl:.0f}%')

        return snapshot

    # -----------------------------------------------------------------
    # Strategy Signal Checks
    # -----------------------------------------------------------------
    def check_strategy_a(self, snap: MarketSnapshot) -> Optional[LiveSignal]:
        """Strategy A: Iron Condor Vol Selling.
        Entry: CRISIS regime, VRP zscore > -0.5, VoV declining, RSI 30-70.
        """
        conditions = []

        if snap.regime != 'CRISIS':
            return None
        conditions.append(f'Regime=CRISIS (RV={snap.rv_cc_30d*100:.1f}%)')

        if snap.vrp_zscore <= -0.5:
            return None
        conditions.append(f'VRP z-score={snap.vrp_zscore:.2f} > -0.5')

        if snap.vov_30d >= snap.vov_5d_avg:
            return None
        conditions.append(f'VoV declining ({snap.vov_30d:.4f} < 5d avg {snap.vov_5d_avg:.4f})')

        if snap.rsi_14 < 30 or snap.rsi_14 > 70:
            return None
        conditions.append(f'RSI={snap.rsi_14:.1f} in [30,70]')

        # Build iron condor
        S = snap.btc_price
        short_call_K = round(S * 1.15, -2)
        short_put_K = round(S * 0.85, -2)
        long_call_K = round(S * 1.25, -2)
        long_put_K = round(S * 0.75, -2)

        size = round(self.equity * 0.05, 6)  # 5% of equity in BTC

        return LiveSignal(
            strategy_name='A_VolSelling_IronCondor',
            signal_type='iron_condor',
            direction='short',
            description=f'Sell iron condor: short {short_put_K:.0f}/{short_call_K:.0f}, '
                        f'long {long_put_K:.0f}/{long_call_K:.0f}, 14 DTE',
            confidence='HIGH' if snap.vrp_zscore > 0 else 'MEDIUM',
            suggested_instrument=f'BTC Iron Condor {short_put_K:.0f}/{short_call_K:.0f}',
            suggested_strike=short_call_K,
            suggested_expiry=(datetime.now(timezone.utc) + timedelta(days=14)).strftime('%Y-%m-%d'),
            option_type='straddle',
            suggested_size_btc=round(size, 6),
            max_loss_usd=round((long_call_K - short_call_K) * size, 2),
            legs=[
                {'type': 'put', 'strike': short_put_K, 'direction': 'sell'},
                {'type': 'put', 'strike': long_put_K, 'direction': 'buy'},
                {'type': 'call', 'strike': short_call_K, 'direction': 'sell'},
                {'type': 'call', 'strike': long_call_K, 'direction': 'buy'},
            ],
            conditions_met=conditions,
        )

    def check_strategy_b(self, snap: MarketSnapshot) -> Optional[LiveSignal]:
        """Strategy B: Momentum Breakout via Long OTM Options.
        Entry: LOW/MEDIUM regime, strong 5d return > 5% or < -5%, RSI > 65 or < 35.
        """
        conditions = []

        if snap.regime not in ('LOW', 'MEDIUM'):
            return None
        conditions.append(f'Regime={snap.regime}')

        # Need strong directional move
        bullish = snap.ret_5d > 0.05 and snap.rsi_14 > 65
        bearish = snap.ret_5d < -0.05 and snap.rsi_14 < 35

        if not bullish and not bearish:
            return None

        if bullish:
            conditions.append(f'Bullish breakout: 5d ret={snap.ret_5d*100:.1f}%, RSI={snap.rsi_14:.1f}')
            opt_type = 'call'
            strike = round(snap.btc_price * 1.10, -2)  # 10% OTM
            desc = f'Buy OTM call @ {strike:.0f} (10% OTM), 21 DTE'
        else:
            conditions.append(f'Bearish breakout: 5d ret={snap.ret_5d*100:.1f}%, RSI={snap.rsi_14:.1f}')
            opt_type = 'put'
            strike = round(snap.btc_price * 0.90, -2)  # 10% OTM
            desc = f'Buy OTM put @ {strike:.0f} (10% OTM), 21 DTE'

        size = round(self.equity * 0.03, 6)  # 3% of equity in BTC

        return LiveSignal(
            strategy_name='B_Momentum_LongOTM',
            signal_type=f'long_otm_{opt_type}',
            direction='long',
            description=desc,
            confidence='MEDIUM',
            suggested_instrument=f'BTC-{strike:.0f}-{opt_type[0].upper()}',
            suggested_strike=strike,
            suggested_expiry=(datetime.now(timezone.utc) + timedelta(days=21)).strftime('%Y-%m-%d'),
            option_type=opt_type,
            suggested_size_btc=round(size, 6),
            max_loss_usd=round(size * snap.btc_price * 0.03, 2),  # Approximate premium
            legs=[{'type': opt_type, 'strike': strike, 'direction': 'buy'}],
            conditions_met=conditions,
        )

    def check_strategy_c(self, snap: MarketSnapshot) -> Optional[LiveSignal]:
        """Strategy C: Event Vol Exploitation.
        C1 (Pre-event short vol): MEDIUM/HIGH regime, IV > 1.15*RV, RSI in 35-65.
        C2 (Post-event long vol): LOW/MEDIUM regime after recent regime change.
        """
        conditions = []

        # C1: Pre-event vol sell (need meaningful RV to compare against)
        if (snap.regime in ('MEDIUM', 'HIGH')
                and snap.rv_cc_30d > 0.05  # Need real RV data
                and snap.iv_30d > snap.rv_cc_30d * 1.15
                and 35 <= snap.rsi_14 <= 65):
            conditions.append(f'Regime={snap.regime}, IV/RV ratio={snap.iv_30d/snap.rv_cc_30d:.2f}')
            conditions.append(f'IV ({snap.iv_30d*100:.1f}%) > 1.15 * RV ({snap.rv_cc_30d*100:.1f}%)')
            conditions.append(f'RSI={snap.rsi_14:.1f} in neutral zone [35-65]')

            strike = round(snap.btc_price, -2)
            size = round(self.equity * 0.04, 6)  # 4% of equity in BTC

            return LiveSignal(
                strategy_name='C_EventVol_PreEvent_ShortStraddle',
                signal_type='short_straddle',
                direction='short',
                description=f'Sell straddle @ {strike:.0f}, IV elevated vs RV, 14 DTE',
                confidence='MEDIUM',
                suggested_instrument=f'BTC-{strike:.0f}-Straddle',
                suggested_strike=strike,
                suggested_expiry=(datetime.now(timezone.utc) + timedelta(days=14)).strftime('%Y-%m-%d'),
                option_type='straddle',
                suggested_size_btc=round(size, 6),
                max_loss_usd=round(size * snap.btc_price * snap.iv_30d * 0.5, 2),
                legs=[
                    {'type': 'call', 'strike': strike, 'direction': 'sell'},
                    {'type': 'put', 'strike': strike, 'direction': 'sell'},
                ],
                conditions_met=conditions,
            )

        # C2: Post-event long vol (after regime transition to LOW/MEDIUM)
        if snap.regime in ('LOW', 'MEDIUM') and snap.days_in_regime <= 7:
            conditions.append(f'Recent regime transition to {snap.regime} ({snap.days_in_regime}d ago)')
            conditions.append(f'Post-event vol buying opportunity')

            strike = round(snap.btc_price, -2)
            size = round(self.equity * 0.03, 6)  # 3% of equity in BTC

            return LiveSignal(
                strategy_name='C_EventVol_PostEvent_LongStraddle',
                signal_type='long_straddle',
                direction='long',
                description=f'Buy straddle @ {strike:.0f}, post-event vol recovery, 21 DTE',
                confidence='MEDIUM',
                suggested_instrument=f'BTC-{strike:.0f}-Straddle',
                suggested_strike=strike,
                suggested_expiry=(datetime.now(timezone.utc) + timedelta(days=21)).strftime('%Y-%m-%d'),
                option_type='straddle',
                suggested_size_btc=round(size, 6),
                max_loss_usd=round(size * snap.btc_price * snap.iv_30d * 0.3, 2),
                legs=[
                    {'type': 'call', 'strike': strike, 'direction': 'buy'},
                    {'type': 'put', 'strike': strike, 'direction': 'buy'},
                ],
                conditions_met=conditions,
            )

        return None

    def check_strategy_d(self, snap: MarketSnapshot) -> Optional[LiveSignal]:
        """Strategy D: Mean Reversion Vol Fade.
        D1 (Short vol): RV percentile > 90%, CRISIS regime 5+ days, RV declining.
        D2 (Long vol): RV percentile < 15%, LOW regime 5+ days.
        """
        conditions = []

        # D1: Short vol after extreme RV
        if (snap.rv_percentile > 90 and snap.regime == 'CRISIS'
                and snap.days_in_regime >= 5):
            # Check if RV is declining (current 7d < 30d suggests mean reversion starting)
            if snap.rv_cc_7d < snap.rv_cc_30d:
                conditions.append(f'RV pctl={snap.rv_percentile:.0f}% > 90%')
                conditions.append(f'CRISIS for {snap.days_in_regime}d (>=5)')
                conditions.append(f'RV declining (7d={snap.rv_cc_7d*100:.1f}% < 30d={snap.rv_cc_30d*100:.1f}%)')

                strike = round(snap.btc_price, -2)
                size = round(self.equity * 0.04, 6)  # 4% of equity in BTC

                return LiveSignal(
                    strategy_name='D_MeanReversion_ShortVol',
                    signal_type='short_straddle',
                    direction='short',
                    description=f'Sell straddle @ {strike:.0f}, extreme RV mean-reverting, 14 DTE',
                    confidence='HIGH' if snap.rv_percentile > 95 else 'MEDIUM',
                    suggested_instrument=f'BTC-{strike:.0f}-Straddle',
                    suggested_strike=strike,
                    suggested_expiry=(datetime.now(timezone.utc) + timedelta(days=14)).strftime('%Y-%m-%d'),
                    option_type='straddle',
                    suggested_size_btc=round(size, 6),
                    max_loss_usd=round(size * snap.btc_price * snap.rv_cc_30d * 0.5, 2),
                    legs=[
                        {'type': 'call', 'strike': strike, 'direction': 'sell'},
                        {'type': 'put', 'strike': strike, 'direction': 'sell'},
                    ],
                    conditions_met=conditions,
                )

        # D2: Long vol after suppressed RV
        if (snap.rv_percentile < 15 and snap.regime == 'LOW'
                and snap.days_in_regime >= 5):
            conditions.append(f'RV pctl={snap.rv_percentile:.0f}% < 15%')
            conditions.append(f'LOW regime for {snap.days_in_regime}d (>=5)')
            conditions.append(f'Vol expansion expected from suppressed levels')

            strike = round(snap.btc_price, -2)
            size = round(self.equity * 0.03, 6)  # 3% of equity in BTC

            return LiveSignal(
                strategy_name='D_MeanReversion_LongVol',
                signal_type='long_straddle',
                direction='long',
                description=f'Buy straddle @ {strike:.0f}, suppressed RV expansion expected, 21 DTE',
                confidence='MEDIUM',
                suggested_instrument=f'BTC-{strike:.0f}-Straddle',
                suggested_strike=strike,
                suggested_expiry=(datetime.now(timezone.utc) + timedelta(days=21)).strftime('%Y-%m-%d'),
                option_type='straddle',
                suggested_size_btc=round(size, 6),
                max_loss_usd=round(size * snap.btc_price * snap.iv_30d * 0.3, 2),
                legs=[
                    {'type': 'call', 'strike': strike, 'direction': 'buy'},
                    {'type': 'put', 'strike': strike, 'direction': 'buy'},
                ],
                conditions_met=conditions,
            )

        return None

    # -----------------------------------------------------------------
    # Full Scan
    # -----------------------------------------------------------------
    def scan(self) -> Tuple[MarketSnapshot, List[LiveSignal]]:
        """Run full market scan: fetch data, compute indicators, check all strategies."""
        print('='*60)
        print('BTC OPTIONS SIGNAL ENGINE - LIVE SCAN')
        print('='*60)

        snapshot = self.build_snapshot()
        signals = []

        print('\nChecking strategy signals...')

        # Strategy A: Iron Condor Vol Selling
        sig_a = self.check_strategy_a(snapshot)
        if sig_a:
            signals.append(sig_a)
            print(f'  [SIGNAL] Strategy A: {sig_a.description}')
        else:
            print(f'  Strategy A: No signal (regime={snapshot.regime}, need CRISIS)')

        # Strategy B: Momentum Breakout
        sig_b = self.check_strategy_b(snapshot)
        if sig_b:
            signals.append(sig_b)
            print(f'  [SIGNAL] Strategy B: {sig_b.description}')
        else:
            print(f'  Strategy B: No signal (5d ret={snapshot.ret_5d*100:.1f}%, RSI={snapshot.rsi_14:.1f})')

        # Strategy C: Event Vol
        sig_c = self.check_strategy_c(snapshot)
        if sig_c:
            signals.append(sig_c)
            print(f'  [SIGNAL] Strategy C: {sig_c.description}')
        else:
            print(f'  Strategy C: No signal')

        # Strategy D: Mean Reversion
        sig_d = self.check_strategy_d(snapshot)
        if sig_d:
            signals.append(sig_d)
            print(f'  [SIGNAL] Strategy D: {sig_d.description}')
        else:
            print(f'  Strategy D: No signal (RV pctl={snapshot.rv_percentile:.0f}%)')

        # Apply confidence-weighted sizing to each signal
        scorer = ConfidenceScorer()
        for sig in signals:
            conf_score = scorer.score(sig, snapshot)
            adjusted_size = round(sig.suggested_size_btc * conf_score, 6)
            adjusted_loss = round(sig.max_loss_usd * conf_score, 2)
            print(f'\n  Confidence adjustment for {sig.strategy_name}:')
            print(f'    Base size: {sig.suggested_size_btc:.6f} BTC')
            print(f'    Confidence score: {conf_score:.4f}')
            print(f'    Adjusted size: {adjusted_size:.6f} BTC')
            # Update signal with adjusted values
            sig.suggested_size_btc = adjusted_size
            sig.max_loss_usd = adjusted_loss
            sig.confidence_score = conf_score  # Store numeric score

        print(f'\nScan complete: {len(signals)} signal(s) detected')
        return snapshot, signals


# ---------------------------------------------------------------------------
# Confidence Scorer — multi-factor sizing multiplier
# ---------------------------------------------------------------------------
class ConfidenceScorer:
    """Scores signal confidence 0.0-1.0 based on multiple market factors.

    Used as a sizing multiplier: size *= confidence_score
    This makes position sizes variable based on conviction level.
    """

    @staticmethod
    def score(signal, snapshot=None) -> float:
        """Compute confidence score 0.0-1.0 from signal + market context.

        Factors:
        1. Base confidence label (HIGH/MEDIUM/LOW) — 40% weight
        2. VRP alignment — 20% weight  
        3. Regime duration — 20% weight
        4. IV/RV convergence — 20% weight

        Returns a score between 0.3 (minimum) and 1.0 (maximum).
        """
        # Factor 1: Base confidence from strategy logic (40% weight)
        conf_map = {'HIGH': 1.0, 'MEDIUM': 0.65, 'LOW': 0.35}
        if hasattr(signal, 'confidence'):
            base = conf_map.get(signal.confidence, 0.5)
        elif isinstance(signal, dict):
            base = conf_map.get(signal.get('confidence', ''), 0.5)
        else:
            base = 0.5

        if snapshot is None:
            return max(0.3, base)

        # Factor 2: VRP alignment (20% weight)
        # Positive VRP favors short vol, negative favors long vol
        direction = getattr(signal, 'direction', None) or (signal.get('direction') if isinstance(signal, dict) else None)
        vrp = getattr(snapshot, 'vrp_30d', 0) if hasattr(snapshot, 'vrp_30d') else 0
        if direction == 'short' and vrp > 0:
            vrp_score = min(1.0, 0.5 + vrp * 5)  # Positive VRP helps shorts
        elif direction == 'long' and vrp < 0:
            vrp_score = min(1.0, 0.5 + abs(vrp) * 5)  # Negative VRP helps longs
        else:
            vrp_score = 0.4  # Misaligned VRP

        # Factor 3: Regime duration (20% weight)
        # Longer regime = more confidence for mean-reversion, less for trend
        days_in = getattr(snapshot, 'days_in_regime', 0) if hasattr(snapshot, 'days_in_regime') else 0
        strat_name = getattr(signal, 'strategy_name', '') or (signal.get('strategy_name', '') if isinstance(signal, dict) else '')
        if 'MeanReversion' in strat_name or 'VolSelling' in strat_name:
            regime_score = min(1.0, 0.4 + days_in * 0.06)  # Longer = better for mean reversion
        else:
            regime_score = max(0.3, 1.0 - days_in * 0.05)  # Shorter = better for breakouts

        # Factor 4: IV/RV convergence (20% weight)
        iv = getattr(snapshot, 'iv_30d', 0) if hasattr(snapshot, 'iv_30d') else 0
        rv = getattr(snapshot, 'rv_cc_30d', 0) if hasattr(snapshot, 'rv_cc_30d') else 0
        if rv > 0 and iv > 0:
            iv_rv_ratio = iv / rv
            if direction == 'short':
                # Short vol loves high IV/RV ratio
                ivr_score = min(1.0, 0.3 + (iv_rv_ratio - 1.0) * 0.7) if iv_rv_ratio > 1.0 else 0.3
            else:
                # Long vol prefers low IV/RV (cheap options)
                ivr_score = min(1.0, 0.3 + (1.0 - iv_rv_ratio) * 1.5) if iv_rv_ratio < 1.0 else 0.4
        else:
            ivr_score = 0.5

        # Weighted combination
        raw = base * 0.40 + vrp_score * 0.20 + regime_score * 0.20 + ivr_score * 0.20

        # Clamp to [0.3, 1.0] — never zero out a signal, never exceed 100%
        return round(max(0.3, min(1.0, raw)), 4)
